ui:
  ssl: ${DSPACE_UI_SSL}
  host: ${DSPACE_UI_HOST}
  port: ${DSPACE_UI_PORT}
  namespace: ${DSPACE_UI_NAMESPACE}
rest:
  ssl: ${DSPACE_REST_SSL}
  host: ${DSPACE_REST_HOST}
  port: ${DSPACE_REST_PORT}
  namespace: ${DSPACE_REST_NAMESPACE}

useProxies: false
