ui:
  ssl: false
  host: 0.0.0.0      # <--- Правильно: Слухаємо всюди
  port: 8081         # Порт, на якому висить Node.js
  namespace: /
  nameSpace: /
  useProxies: false

rest:
  ssl: false
  host: localhost    # <--- ВИПРАВЛЕНО: Клієнт стукає сюди (через Nginx)
  port: 8081         # Зовнішній порт Nginx
  namespace: /server
  nameSpace: /server

useProxies: false